builds:
  - env:
      - CGO_ENABLED=0
    id: "goverview"
    binary: goverview
    goos:
      - linux
      - darwin
      - windows
    ldflags: -s -w -X main.version={{.Version}} -X "main.installFrom=Binary"
archives:
  - format_overrides:
      - goos: windows
        format: zip
changelog:
  use: github
  filters:
    exclude:
    - Merge pull request
    - Merge remote-tracking branch
    - Merge branch
brews:
  - tap:
      owner: bayashi
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
    folder: Formula
    homepage: https://github.com/bayashi/goverview
    description: Display an overview as ASCII tree for a Golang project
    test: |
      system "#{bin}/goverview", '--version'