builds:
  - env:
      - CGO_ENABLED=0
    id: "goverview"
    binary: goverview
    goos:
      - linux
      - darwin
      - windows
archives:
  - format_overrides:
      - goos: windows
        format: zip
brews:
  - tap:
      owner: bayashi
      name: homebrew-goverview
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
    folder: Formula
    homepage: https://github.com/bayashi/goverview
    description: Display an overview as ASCII tree for a Golang project
    test: |
      system "#{bin}/goverview", './'