name: main

on:
  push:
    branches:
      - '*'
    tags-ignore:
      - '*'
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Setup Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.19'
      - name: Install dependencies
        run: go get .
      - name: Build
        run: go build -v ./...
      - name: Test with the Go CLI
        run: go test -v ./...
      - name: Run vet
        run: go vet -v ./...
      - name: Check diff of gofmt
        run: |
            gofmt -s -w . && git diff --exit-code
      - name: Setup staticcheck
        uses: dominikh/staticcheck-action@v1.3.1
        with:
          version: "2023.1.6"
          install-go: false
          min-go-version: '1.19'
          cache-key: '1.19'
      - name: Run staticcheck
        run: staticcheck ./...
